### ISSUE TITLE
error running build file

### ISSUE THREAD

**Issue by vedanjalip** [mrisc32/mrisc32-gnu-toolchain#1]
"Failed to build: Stopped on line 149"
This was the error showing up

**Comment by mbitsnbites** [comment]
Cool! A user! 🕺

Check out/binutils/build.log for more detailed info (if possible).

It may be that you're missing some prerequisites. I have not determined exactly what you need.

For Ubuntu 18.04 I *think* that you need at least the following packages:

* build-essential
* flex
* bison
* libbison-dev
* libgmp-dev
* libmpfr-dev
* libmpc-dev
* texinfo

Out of curiosity: What's your interest in MRISC32?

**Comment by vedanjalip** [comment]
Hello,
 Thanks for the reply, I was working on a project to simulate rtl code in
riscv processor. I've tried multiple riscv processors but wasn't successful
in simulation. I will try installing packages. I am using ubuntu 16.04 btw.

**Comment by mbitsnbites** [comment]
Ok, so it may come as a disappointment then that this toolchain is not for RISC-V, but for [MRISC32](https://github.com/mrisc32/mrisc32), which is a different instruction set.
